### ISSUE TITLE
Research zKSNARKs Blocker: Circom GPL license

### ISSUE THREAD

**Issue by oskarth** [vacp2p/research#12]
# Problem

Currently Circom https://github.com/iden3/circom/blob/master/COPYING uses a GPL license, which can get tricky when it comes to the App Store etc.

## Acceptance criteria

1. Use library which has more permissive license (MIT/Apache)
2. Confidence that using GPL code wouldn't cause any issues in this case

## Notes

Bellman uses a dual MIT/Apache license, just like Nimbus https://github.com/zkcrypto/bellman#license

**Comment by barryWhiteHat** [comment]
I think the actual blocker is websnark because circom get "compiled" to proving key and verification key so you don't include circom in your lib except witness generation logic which is compiled to wasm IIUC

**Comment by barryWhiteHat** [comment]
github.com/kilic/rlnapp is written with bellman with is mit IIUC.

**Comment by oskarth** [comment]
Closing as this is no longer a blocker.
