### ISSUE TITLE
Analysis: Waku Relay scaling (part 1)

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#158]
Anaylsis based on simplified assumptions:
 How does a single pubsub mesh scale, including an outlook towards what topic sharding can achieve.

**Comment by corpetty** [comment]
tagging Distributed Systems Testing team: @AlbertoSoutullo, @0xFugue, @Daimakaimura

**Comment by AlbertoSoutullo** [comment]
Hi, how can we have access to that?
