### ISSUE TITLE
Roadmap(SeM): Application Protocols

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#165]
## Background / Motivation

This roadmap is part of Vac Secure Messaging (SeM).
It lists work on protocols running on Waku core protocols and components.

## Status 1 mio users Milestone

* [x] #166
  - [ ] #177
* [x] #167
* [x] #168
  - [ ]  RFC 55/STATUS-1TO1-CHAT : add section on private group chat

[Overview over the integration of these tasks into the Status MVP](https://github.com/waku-org/pm/issues/12#issuecomment-1403577619)

## Milestones and Issues

* [ ] Waku e2e messaging
  - based on Status 1:1 chat
  - efficient, scaling, privacy/anonymity preserving 1:1 messaging on top of sharded Waku Relay
* [ ] secure group messaging based on Waku e2e messaging
  - based on Status group chat

**Comment by rymnc** [comment]
Should we also move [5/SECURE-TRANSPORT](https://specs.status.im/spec/5) as an alternative to [35/WAKU2-NOISE](https://rfc.vac.dev/spec/35/)?
