### ISSUE TITLE
raw RFC(standards): Status 1:1 chat

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#168]
This issue is part of the SeM application protocols roadmap #165 and  tracks specifying the current Status 1:1 chat protocol, which runs on [11/WAKU2-RELAY](https://rfc.vac.dev/spec/11/), in a Vac RFC. (named similar to XX/STATUS-1to1-CHAT)

* This RFC should cover [5/SECURE-TRANSPORT](https://specs.status.im/spec/5)

Open PR: https://github.com/vacp2p/rfc/pull/569

### Outlook

In the future, XX/STATUS-1to1-CHAT should run over *Waku e2e messaging*, a protocol that offers secure end-to-end communication channels (see future Milestones of #165)

**Comment by rymnc** [comment]
@kaiserd can we close this?
