### ISSUE TITLE
Roadmap(SeM): Protocol Incentivization

### ISSUE THREAD

**Issue by kaiserd** [vacp2p/research#171]
## Background / Motivation

The *protocol incentivization* track covers research on incentives for nodes to offer specific services and/or resources.

Part of this is research on services credentials.
The goal is allowing service consumers to purchase *service credentials* (or tokens) that can be used to obtain services from Waku nodes. Service providers will be able to claim funds associated with received credentials.

## Issues

(This roadmap is WIP. Items on the roadmap, especially ones farther in the future, might change.)

* [ ] raw RFC: service credentials
  - see #99

**Comment by fryorcraken** [comment]
Relevant to the discussion: https://forum.vac.dev/t/waku-payment-models/166/3

I think platforms are likely to want to be the one to pay for the infra as they are extracted value from their users in some other form.

While "user paying" is also a viable model, I think we could almost see it as a "2nd" option.
