### ISSUE TITLE
Research discv5 Blocker: ENR lookup

### ISSUE THREAD

**Issue by decanus** [vacp2p/research#27]
# Problem

It currently seems like there is an issue with finding a specific field in ENRs, although it gets added correctly to the ENR itself, when a node ends up doing a lookup and checks to see if the field exists it never does.

# Acceptance Criteria

This bug is resolved investigated and resolved nim-eth. Finally the test is rexecuted using this fixed version providing more insight.

# Notes
 - The pull request for ENR lookup: https://github.com/vacp2p/research/pull/25

**Comment by oskarth** [comment]
Motivation is missing here. The reason for doing something like this is that you don't have to connect to all nodes, but can be aware of them in terms of what you get as response.

As a back of the envelope calc, you'd get an order of magnitude of more nodes based on being aware of their ENR vs having to connect to them specifically. More precise estimates can probably be gathered here, depending on specific Kad configuration.

**Comment by oskarth** [comment]
Why was this closed?

**Comment by decanus** [comment]
@oskarth because the ENR issue was resolved.

**Comment by oskarth** [comment]
It'd be good with a comment saying what has changed and link to relevant issue
