### ISSUE TITLE
Research discv5 Blocker: Accurate estimations on network

### ISSUE THREAD

**Issue by decanus** [vacp2p/research#28]
# Problem

Currently there are now estimations on the network, we do not know how many people we expect to participate in the DHT, what the distribution of these nodes is etc.

# Acceptance Criteria

We have these estimations which will be able to provide us with more accurate numbers that we can evaluate discv5 with.

**Comment by oskarth** [comment]
I think we can get pretty far with back of the envelope calculations. E.g. let's say we want to support a million users, and we expect 1 or 10% to run core infrastructure with adaptive nodes. That would mean 10k nodes.

It should also be fairly straightforward to test multiple orders of magnitude here, at least theoretically. E.g. with an analysis such as: 
![image](https://user-images.githubusercontent.com/1552237/79543821-9f206d00-80c0-11ea-9463-406b23a9e591.png)

For a simulation we will probably have to restrict ourselves to toy models for now. If there's a specific need for large scale realistic network studies we can isolate that in a specific issue, and there's probably a lot of overlap with Eth2/IPFS etc studies.

The network estimate breaks down into:
- orders of magnitude analysis (10, 100, 1k, 10k, 100k, 1m nodes)
- concentration of nodes of different capabilities (e.g. 1% full nodes, 10%, etc) [for simplicity just looking at one dimension of concentration here]
