### ISSUE TITLE
Blockscience model: Break it

### ISSUE THREAD

**Issue by oskarth** [vacp2p/research#34]
## Problem

Umbrella issue: https://github.com/vacp2p/research/issues/33

We have a model from Blockscience we don't understand. One way of understanding it is to "break it". I.e. understand what its assumptions are and how that might map to the real world.

## Acceptance criteria

Outline example of where it "breaks". This might be a misunderstanding of the model, but it can be used to feed back into BS calls and to improve clarity/model/understanding.

The end goal should be to be confident it maps sufficiently to the real world, as we best understand it.

**Comment by oskarth** [comment]
I'll have a look at it from this angle and see if it helps with my understanding.

**Comment by dryajov** [comment]
It would be beneficial to have a plain English walkthrough of what they are modeling as well as docs about what each section of the model is doing - can be comments in code (there are some and they are helpful, but definitely incomplete).

**Comment by cammellos** [comment]
https://notes.status.im/blockscience-code-comment has a note for each action taken in the model.

**Comment by oskarth** [comment]
My current questions https://notes.status.im/a5qHKXldQQy5yRfq6mDJng# - asked for async written reply

**Comment by oskarth** [comment]
Current intuition is that there are way too many chain ops which is unrealistic for Ethereum. To address this we'd need to decouple accounting and settlement more, but unclear what implications this has.

Also skeptical of the static network topology in examples, doesn't seem realistic from a p2p pov and likely here-be-dragons.

Above not hard data though, so after Qs answered the above could hopefully be clarified more and become more objective.

**Comment by oskarth** [comment]
I'd consider this done.
