### ISSUE TITLE
Waku v2 usage survey

### ISSUE THREAD

**Issue by oskarth** [vacp2p/research#45]
(Card converted into issue to discuss)

# Problem

We want to have a survey of Waku v2 potential usage so we know we are building the right thing.

# Issues
- [x] questions created
- [x] sent to ~3 projects
- [ ] wait and ping for response
- [ ] collect and summarize findings
- [ ] follow up questions

**Comment by oskarth** [comment]
@decanus converted into issue so we can follow up and ensure we finish it properly. Could you please post what we have now, what next steps are and what's missing?

**Comment by oskarth** [comment]
@decanus Ping, what is happening with this ?

**Comment by oskarth** [comment]
No update for a week, assumed not being worked on.

**Comment by oskarth** [comment]
Dean to post summary here.

**Comment by decanus** [comment]
- https://notes.status.im/-rk_dmlORKeRN1CKrIdJfQ
 - https://notes.status.im/WzdZdnTuRSGjWTF4LKlrzA

Here are the first 2 results. Will post summary soon.

**Comment by oskarth** [comment]
Where is this summary @decanus?

**Comment by decanus** [comment]
# Summary

Something iterated by both of the surveys is that they need browser versions. Both parties are open to running a node. Both of the use cases are essentially for application level messaging. Not for user to user messaging. So M2M. Waku being flexible also seems like a major concern.

**Comment by oskarth** [comment]
Thanks. Aight, I think a mini write up for forum would be nice but not sure we have bandwidth. I've asked John if he is able to push this for us to get more data. I think for now we have enough to go on and we can revisit as appropriate. Closing.

Do you have a link to the OpenVASP forum post by any chance?
